### ISSUE TITLE
Zmiany w stosowaniu terminów

### ISSUE THREAD

**Issue by Eccenux** [Eccenux/wiki-DYKCzyWiesz#10]
Po dyskusji w barze i okolicy okazało się, że termin 30 dni od rozbudowy tak nie do końca obowiązuje w praktyce. Coś trzeba zrobić z głównym oknem, żeby to odzwierciedlić. Trzeba też zmienić też start licznika. Trochę zmienia to koncepcję i część zmian już wprowadzonych było niepotrzebnych... Ale w sumie może tak będzie prościej.

- [x] Start licznika wg daty zgłoszenia, a nie data rozbudowy (czyli nie według instrukcji jednak).
- [x] Może data powinna być nieaktywna jak podpis? (szare tło, read-only) -> jednak wyrzucone całkiem (zostaje w dymku i na liście zmian)
- [x] Przejrzeć opisy w title `(!)` i `?`.

![obraz](https://github.com/Eccenux/wiki-DYKCzyWiesz/assets/1045235/df35ac53-41fe-40fe-ac07-6f20cfe7dca2)

**Comment by Kaligula0** [comment]
Gdyby skrypt prawidłowo określał datę w 100% przypadków to data powinna być szara/nieaktywna. Zostawiłem to pole jako edytowalne celowo, aby użytkownik mógł poprawić skrypt w przypadku błędu. Nie sądzę, że skrypt jest w stanie w 100% przypadków ocenić prawidłowo, ale jeśli się mylę, to śmiało możemy tak zrobić, uznać i wyszarzyć :)

**Comment by Kaligula0** [comment]
Poza tym nie przyszło mi do głowy, żeby ktoś mógł to pole nadużywać 🤔

**Comment by Kaligula0** [comment]
Ale termin "10d od dnia utworzenia/rozbudowy" obowiązuje i można go wciąż stosować w gadżecie?

**Comment by Eccenux** [comment]
> Gdyby skrypt prawidłowo określał datę w 100% przypadków to data powinna być szara/nieaktywna. Zostawiłem to pole jako edytowalne celowo, aby użytkownik mógł poprawić skrypt w przypadku błędu. Nie sądzę, że skrypt jest w stanie w 100% przypadków ocenić prawidłowo, ale jeśli się mylę, to śmiało możemy tak zrobić, uznać i wyszarzyć :)

Czy na pewno zawsze może, to nie wiem. Ale wychodzi na to, że ta data ma być tylko informacyjna. W sumie to szkoda, że nie wiedziałem tego zanim nie napisałem na to testów i w ogóle całej osobnej klasy, która sprawdza różne przypadki 🙈🙃
https://github.com/Eccenux/wiki-DYKCzyWiesz/blob/main/test/RevisionList.test.js

**Comment by Kaligula0** [comment]
Z dyskusji w barze zrozumiałem, że zgłoszenia mają nastąpić ≤10d od utworzenia artykułu, tego nikt nie neguje. Podważona została tylko zasadność sztwynego trzymania się terminu 30d.
Jeśli chcemy zostawić pewną swobodę to:
- albo zostawiamy pole białe, żeby user mógł skorygować,
- albo wyszarzone, ale gadżet nie blokuje zgłoszenia tylko wywala komunikat, który każe userowi zastanowić się 2x

**Comment by Eccenux** [comment]
Zmiany po dyskusji gotowe.

- BTW. Podpowiedzi są kompatybilne z dotykowym ekranem.
- BTW. Link do historii pod listą.
