### ISSUE TITLE
Drobiazgi językowe 

### ISSUE THREAD

**Issue by czupirek** [Eccenux/wiki-DYKCzyWiesz#2]
- [x]  Przy komunikacie o błędzie: "Rozmiar 1893 b dyskwalifikuje artykuł ze zgłoszenia!!" --> podwójny wykrzyknik

- [x] Tak samo przy "Brak źródeł dyskwalifikuje artykuł ze zgłoszenia!! (info)"

- [x] "Zgłaszaj hasła nie później niż 10 dni od powstania lub rozbudowania hasła, posiadające źródła najlepiej w formie przypisów i zawierające co najmniej 2 kB samej treści." -->
"Zgłaszaj hasła, które powstały lub zostały rozbudowane nie dawniej niż 10 dni temu, posiadające źródła - najlepiej w formia przypisów oraz zawierające co najmniej 2 kB samej treści."

- [x] przy polu "Data utw./rozbud. artykułu" - tooltip pod wykrzyknikiem po prawej:
Upewnij się[przecinek] czy o tę datę chodzi

- [x] "Pytania zacznij od od" --> "Pytania zacznij od: "
_(to było podchwytliwe, bo oba "od" są w różnych liniach)_

- [x] Przy próbie wysłania zgłoszenia bez źródeł - alert:
(Jeśli źródła są to zwróć uwagę czy tytuł sekcji jest prawidłowy
-->
(Jeśli źródła są, to zwróć uwagę, czy tytuł sekcji jest prawidłowy

Po wysłaniu zgłoszenia:

- [x] Dla pewności możesz sprawdzić **[w swoim wkładzie]**(https://pl.wikipedia.org/wiki/Specjalna:Wk%C5%82ad/Czupirek)**[przecinek]** czy wszystko poszło zgodnie z planem.

- [x] Jeśli coś poszło nie tak**[przecinek]** to [kliknij tutaj](https://pl.wikipedia.org/wiki/Krapczene#), aby wysłać twórcy gadżetu e-mail z opisem błędu, a gadżet dołączy do niego szczegóły techniczne.

- [x] Opisz co się stało. Bez tego twórca nie będzie wiedział co naprawiać.
-->
Opisz, co się stało. Bez tego twórca nie będzie wiedział, co naprawiać.

**Comment by czupirek** [comment]
Jeszcze przy polu "Data utw./rozbud. artykułu" - tooltip pod wykrzyknikiem po prawej: 
Upewnij się[przecinek] czy o tę datę chodzi

**Comment by Eccenux** [comment]
✅✅
