### ISSUE TITLE
Brak potwierdzenia wysłania maila

### ISSUE THREAD

**Issue by czupirek** [Eccenux/wiki-DYKCzyWiesz#3]
Po wysłaniu maila twórcy gadżetu brak potwierdzenia wysłania - bez tego biedny twórca będzie zaspamowan identycznymi zgłoszeniami.

**Comment by Kaligula0** [comment]
Nie neguję Twojego zgłoszenia, ale przyznaję, że przez te wszystkie lata dostałem 4 zgłoszenia ;) Wliczając zgłoszenie testowe Nuxa z zeszłego miesiąca.
